version: '3.2'
services:
  backend1:
      image: rafaelmarques7/hello-node:latest
  backend2:
      image: rafaelmarques7/hello-node:latest
  backend3:
      image: rafaelmarques7/hello-node:latest
  backend4:
      image: rafaelmarques7/hello-node:latest
  backend5:
      image: rafaelmarques7/hello-node:latest
  loadbalancer:
      image: nginx:latest
      links:
          - backend1
          - backend2
          - backend3
          - backend4
          - backend5
      ports:
        - '8080:8080'
      volumes: 
        - ./container-balancer/nginx.conf:/etc/nginx/nginx.conf:ro

# docker-compose useful commands
#
# build (clean):
#     sudo docker-compose build --no-cache
# run:
#     sudo docker-compose up
